// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA16A69uT_P7IzLAyci_spvDJNZopezDFk',
    appId: '1:330751410543:web:8885f782d4aec5611ce89a',
    messagingSenderId: '330751410543',
    projectId: 'easac-task-a2361',
    authDomain: 'easac-task-a2361.firebaseapp.com',
    storageBucket: 'easac-task-a2361.appspot.com',
    measurementId: 'G-6VRFJ0RFZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuU4On_aj3Bfb8iBQaaUG-R9Dka11HMgg',
    appId: '1:330751410543:android:bf4af2e3f73add6f1ce89a',
    messagingSenderId: '330751410543',
    projectId: 'easac-task-a2361',
    storageBucket: 'easac-task-a2361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJgQJ6QAkEZVbvQzlTn_SlYcDva3pr0M',
    appId: '1:330751410543:ios:0b42b78e56dcfecd1ce89a',
    messagingSenderId: '330751410543',
    projectId: 'easac-task-a2361',
    storageBucket: 'easac-task-a2361.appspot.com',
    iosBundleId: 'com.example.easacTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJgQJ6QAkEZVbvQzlTn_SlYcDva3pr0M',
    appId: '1:330751410543:ios:bee5d21f00549df41ce89a',
    messagingSenderId: '330751410543',
    projectId: 'easac-task-a2361',
    storageBucket: 'easac-task-a2361.appspot.com',
    iosBundleId: 'com.example.easacTask.RunnerTests',
  );
}
